# Olá! Seja bem-vindo(a).

Nesse notebook, vamos explorar um pouco mais sobre os algoritmos de `Bellman-Ford` e `Floyd-Warshall`.

Antes de começar a diversão, vamos relembrar algumas coisas...

## Dynamic Programming

É um paradigma associado à solução de problemas (otimização). 

<img src="img/dynamic_programming.jpeg" alt="drawing" width="500"/>

A principal ideia por trás desse conceito, no campo de Algoritmos, é economizar tempo computacional armazenando resultados intermediários. Esse paradigma é aplicado a problemas que têm as seguintes características: 

> - **Subestrutura ótima:** a solução ótima pode ser obtida recursivamente a partir da solução ótima de problemas menores.                                                                                  <br>
> - **Problemas sobrepostos:** há, de fato, ganho em tempo computacional em se armazenar as soluções ótimas dos sub-problemas.                                                                           <br>

Na prática, essa estratégia de otimização segue os seguintes passos: 

> 1. Estruturar o problema (identificar características).
> 2. Caracterizar a estrutura da solução ótima (em função das soluções dos sub-problemas).
> 3. Calcular, recursivamente, a solução ótima dos sub-problemas (Top-Down ou Bottom-Up).
> 4. Construir a solução ótima a partir das informações computadas.


Um problema que, naturalmente, atende todos esses pontos é **encontrar o n-ésimo termo da sequência de Fibonacci**. Vamos relembrar rapidamente como aplicar programação dinâmica a esse problema. 

<img src="img/fibonacci_memoization.png" alt="drawing" width="400"/>


Nesse exemplo, é fácil visualizar o conceito de *memoization*. A principal ideia é armazenar as soluções ótimas dos sub-problemas em uma lista e, à medida em que for preciso, acessar esses resultados em tempo constante.

Vamos aplicar esses conceitos implementando os algoritmos `Bellman-Ford` e `Floyd-Marshall`.

<br>

-----

A ideia por trás desse laboratório é aplicar os conhecimentos transmitidos durante a apresentação (e aprender enquanto nos divertimos programando-os!). 

Preparados? Então vamos lá.

<img src="img/fun.jpg" alt="drawing" width="100"/>

Vamos começar com um import daqueles...

In [1]:
import numpy as np

## Bellman-Ford

<img src="img/Shortest_path_with_direct_weights.svg" alt="drawing" width="300"/>

### Problema:

> a) Dado um grafo e um nó fixo, encontre os menores caminhos do nó escolhido a todos os demais nós no grafo.                                                                                              <br>
> b) O grafo pode conter arestas negativas.

### Pseudo-código: 

> 1. Defina d[u] como uma estimativa da distância entre s e v. 
> 2. Relaxar a aresta (u,v), i.e., diminuir d[v] passando por u, para todos os vizinhos v de u.
> 3. d[v] = min(d[v], d[u] + w(u,v))
> 4. Utiliza sucessivamente relaxamento nas demais arestas do grafo.

### Passo a passo: 

Agora é sua vez! Mas calma, vamos guiá-lo no passo a passo...

Já criamos um grafo e o inicializamos para você!


**Sua tarefa é a seguinte:**

1. Implementar uma função chamada *relax* que toma como argumento um nó, seu vizinho, o grafo, um dicionário de distâncias e um dicionário com os nós predecessores (calma. Sei que parece *overwhelming*, mas já fizemos um *sketch* da função para você.). Essa fução vai fazer o relaxamento de uma dada aresta (atualizar seu peso).                                                                               
<br>

2. Implementar uma função chamada *bellman_ford* que toma como argumentos um grafo e um vértice inicial (*source*), e retorna as menores distâncias do nó inicial para cada um dos outros nós no grafo.


In [2]:
# grafo= {nó1: {vizinho1: distancia1, vizinho2: distancia2} }  # direcionado: arestas saem do nó1 

graph = {
    'a': {'b': 4, 'c':  2},
    'b': {'c': 5, 'd':  10},
    'c': {'e': 3},
    'd': {'f':  11},
    'e': {'d': 4},
    'f': {}
    }

print('Grafo Criado!')
print('\n')
print(graph)

Grafo Criado!


{'a': {'b': 4, 'c': 2}, 'b': {'c': 5, 'd': 10}, 'c': {'e': 3}, 'd': {'f': 11}, 'e': {'d': 4}, 'f': {}}


In [16]:
# Inicializa o grafo
# Para cada nó, preparamos o predecessor e o destino
def initialize(graph, source):
    d = {} # distâncias
    p = {} # nós predecessores
    for node in graph:
        d[node] = float('Inf') # Nós não conectados estão muito distantes (dist. infinita)
        p[node] = None
    d[source] = 0 # Distância do nó inicial (fonte) é 0.
    return d, p

# Relaxamento (reclina a cadeira... rsrs)
def relax(node, neighbour, graph, d, p):
    # Se a distância entre o nó e o vizinho é menor que a que está armazenada
    # você pode fazer um if ou aplicar direto seguinte statement:
    # distance[j] = min(distance[j], distance[i] + weight(i, j))
    # OBS: se optar pela segunda abordagem, não esqueça de atualizar o dicionadio de predecessores
    # basta fazer: p[neighbour] = node
    
    ### Seu código aqui


    ### Fim do seu código (OBS: não precisa retornar nada. Idealmente, essa função é inplace)
        
def bellman_ford(graph, source):
    d, p = initialize(graph, source)  # inicializa o grafo 
    for i in range(len(graph)-1): # Para cada nó...
        # lembre que o algoritmo atualiza os pesos em cada aresta n-1 vezes, 
        # onde n é o número de vértices
        # dica: para cada nó e cada um de seus vizinhos, queremos relaxar(nó,vizinho, no grafo, d, p)

        ### Seu código aqui   (Qualquer dúvida, chame os monitores - Franklin e Lucas)

        
        
        ### Fim do seu código (não precisa alterar nada abaixo dessa linha)

    # Checa se há ciclos negativos 
    for u in graph:
        for v in graph[u]:
            assert d[v] <= d[u] + graph[u][v]

    return d, p

Se tudo deu certo até aqui, o seguinte código deve compilar e mostrar as menores distâncias.

In [28]:
d, p = bellman_ford(graph, 'a')

print 'Predecessores:', p
print '\nDistâncias (a partir do nó escolhido - source):', d 

Predecessores: {'a': None, 'b': 'a', 'c': 'a', 'd': 'e', 'e': 'c', 'f': 'd'}

Distâncias (a partir do nó escolhido - source): {'a': 0, 'b': 4, 'c': 2, 'd': 9, 'e': 5, 'f': 20}


<br>

## Floyd-Warshall

Lembre que, para implementar esse algoritmo, é mais conveniente escrever o grafo na forma de uma matriz de adjacência. 

<img src="img/adjacent_matrix.png" alt="drawing" width="550"/>

### Problema: 

Encontrar a menor distância entre TODOS os pares de nós presentes no grafo.


### Pseudo-código:

1. Seja $G(V,E)$ um grafo com pesos e sejam $u, v \in V$. 
2. Para cada vértice, atribua um único valor entre $\{1, … ,|V|\}$. 
3. Para cada $k \in \{1, … ,|V|\}$, defina $D_k[u,v]$ como o valor do menor caminho entre $u$ e $v$ que passa pelos vértices ${1,...,k-1}$. Defina $D_0[u,v]$ como o valor do caminho entre $u$ e $v$ composto por apenas uma aresta.
4. Armazene uma matriz $D_k$, com os valores de $D_k[u,v]$, para todos os pares $(u,v) \in V×V$.

### Passo a passo:

Chegou a tão esperada hora de implementar o algoritmo de `Floyd-Warshall`. 

Note que já fizemos alguns preparativos para você. Criamos um grafo e definimos alguns parâmetros iniciais... Agora é a sua vez. 

Sua tarefa é a seguinte:

1. Definir uma função chamada floyd_warshall que recebe uma matriz de adjacências e retorna uma matriz de mesma dimensão, onde cada elemento reflete a menor distância do nó i para o nó j.

2. Lembre que, quando o nó k é escolhido como source, as distâncias são atualizadas da seguinte forma:
$$ D_k[u,v] = min\{D_{k-1}[u,v], D_{k-1}[u,k] + D_{k-1}[k,v]\} $$

DICA: já fizemos o primeiro for para você! (cada nó é escolhido como pivô (source). Agora resta atualizar as distâncias...

In [107]:
# definindo grafo (matriz de adjacências)
graph = [    [0, 5, INF, 10, -2], 
             [INF, 0, 3, INF, 14], 
             [INF, INF, 0, 1, 2] , 
             [INF, INF, INF, 0, -1],
             [INF, 2, 1, INF, 10]     ] 

# Número de vértices no Grafo
V = 5 

# representa Infinito
INF  = float('Inf')

In [110]:
def floyd_warshall(graph): 
  
    dist = np.array(list(map(lambda i : list(map(lambda j : j , i)) , graph)))
    print 'Matriz de adjacência: '
    print dist 

    for k in range(V): 
        # escolhe todos os vértices como source, um por um 
        # descomente as duas linhas abaixo se quiser ver o passo a passo
        print('\n\tSource: Nó',k)
        print(dist)
        
        ### Seu código aqui      (Qualquer dúvida, chame os monitores - Franklin e Lucas)

        
        ### Fim do seu código (não precisa alterar nada abaixo dessa linha)
    
    # esses prints já estão com parênteses
    print('\n')
    print('Resultado (matriz com menores distâncias):')
    print(dist)

Agora é a hora da verdade...

In [111]:
floyd_warshall(graph) 

Matriz de adjacência: 
[[ 0.  5. inf 10. -2.]
 [inf  0.  3. inf 14.]
 [inf inf  0.  1.  2.]
 [inf inf inf  0. -1.]
 [inf  2.  1. inf 10.]]

	Source: Nó 0
[[ 0.  5. inf 10. -2.]
 [inf  0.  3. inf 14.]
 [inf inf  0.  1.  2.]
 [inf inf inf  0. -1.]
 [inf  2.  1. inf 10.]]

	Source: Nó 1
[[ 0.  5. inf 10. -2.]
 [inf  0.  3. inf 14.]
 [inf inf  0.  1.  2.]
 [inf inf inf  0. -1.]
 [inf  2.  1. inf 10.]]

	Source: Nó 2
[[ 0.  5.  8. 10. -2.]
 [inf  0.  3. inf 14.]
 [inf inf  0.  1.  2.]
 [inf inf inf  0. -1.]
 [inf  2.  1. inf 10.]]

	Source: Nó 3
[[ 0.  5.  8.  9. -2.]
 [inf  0.  3.  4.  5.]
 [inf inf  0.  1.  2.]
 [inf inf inf  0. -1.]
 [inf  2.  1.  2.  3.]]

	Source: Nó 4
[[ 0.  5.  8.  9. -2.]
 [inf  0.  3.  4.  3.]
 [inf inf  0.  1.  0.]
 [inf inf inf  0. -1.]
 [inf  2.  1.  2.  1.]]


Resultado (matriz com menores distâncias):
[[ 0.  0. -1.  0. -2.]
 [inf  0.  3.  4.  3.]
 [inf  2.  0.  1.  0.]
 [inf  1.  0.  0. -1.]
 [inf  2.  1.  2.  1.]]


## Fim! Espero que vocês tenham gostado.